-- #5 报表索引核查补口：YKT_BATCH.PROJECT_ID 外键列建索引。
-- 报表按项目过滤走 SELECT ID FROM YKT_BATCH WHERE PROJECT_ID=?，且 Oracle 未索引外键
-- 在父表(YKT_PROJECT) DML 时会对子表(YKT_BATCH)加全表锁。幂等：存在则跳过。
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_BATCH_PROJECT';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BATCH_PROJECT ON YKT_BATCH (PROJECT_ID)';
  END IF;
END;
/
