-- 补贴项目补「联系人 / 联系方式」两列。生产的项目维护表单上有这两个字段（追踪代码同一行右侧），
-- 本系统的 YKT_PROJECT 一直缺列，表单也没做——本次对齐生产表单时补上。
--
-- 非必填：生产上这两项没有红星，历史项目留空即可，不做回填。
-- 幂等：逐列判断存在性，重复执行零改动。

DECLARE
  v NUMBER;
BEGIN
  SELECT COUNT(*) INTO v FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'YKT_PROJECT' AND COLUMN_NAME = 'CONTACT_NAME';
  IF v = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE YKT_PROJECT ADD (CONTACT_NAME VARCHAR2(50 CHAR))';
  END IF;

  SELECT COUNT(*) INTO v FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'YKT_PROJECT' AND COLUMN_NAME = 'CONTACT_PHONE';
  IF v = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE YKT_PROJECT ADD (CONTACT_PHONE VARCHAR2(50 CHAR))';
  END IF;
END;
/
