-- =====================================================================
-- 一卡通管理模块 Oracle 11g 建表脚本（全量结构，幂等：先 DROP 再 CREATE）
-- 雪花 ID 由应用层生成，主键无序列。结构对齐运行库导出的权威 DDL。
-- =====================================================================

BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
      'SYS_USER','SYS_ROLE','SYS_MENU','SYS_ORG','SYS_USER_ROLE','SYS_ROLE_MENU','SYS_USER_PROJECT',
      'YKT_BANK','YKT_VILLAGE','YKT_PROJECT','YKT_BENEFICIARY','YKT_NOTICE','YKT_BATCH','YKT_ROSTER',
      'YKT_GRANT_DETAIL','YKT_PROJECT_QUOTA','YKT_PAYMENT_APPLY','YKT_AUDIT_LOG','YKT_PROJECT_POLICY',
      'YKT_INDICATOR','YKT_PAY_APPLY_DETAIL','YKT_POLICY','YKT_PROJECT_AUDIT_LOG',
      'YKT_AGENCY','YKT_CENTRAL_PROJECT','YKT_OFFICE','YKT_TPL_ITEM','YKT_STD_ITEM'))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- ============ 安全 / 组织 ============
CREATE TABLE SYS_USER (
  ID            NUMBER(19)   PRIMARY KEY,
  ORG_ID        NUMBER(19),
  USERNAME      VARCHAR2(64) NOT NULL,
  PASSWORD      VARCHAR2(128),
  REAL_NAME     VARCHAR2(64),
  PHONE         VARCHAR2(32),
  EMAIL         VARCHAR2(128),
  ID_CARD       VARCHAR2(32),
  USER_TYPE     VARCHAR2(32),
  STATUS        NUMBER(1)    DEFAULT 1,
  LAST_LOGIN_AT TIMESTAMP,
  TENANT_ID     NUMBER(19),
  CREATE_TIME   TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0
);

CREATE TABLE SYS_ROLE (
  ID          NUMBER(19)   PRIMARY KEY,
  ROLE_CODE   VARCHAR2(64),
  ROLE_NAME   VARCHAR2(128),
  REMARK      VARCHAR2(255),
  STATUS      NUMBER(1)    DEFAULT 1,
  TENANT_ID   NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0,
  DATA_SCOPE  VARCHAR2(20) DEFAULT 'ALL'
);

CREATE TABLE SYS_MENU (
  ID         NUMBER(19)   PRIMARY KEY,
  PARENT_ID  NUMBER(19),
  MENU_CODE  VARCHAR2(64),
  MENU_NAME  VARCHAR2(128),
  MENU_TYPE  VARCHAR2(8),
  PATH       VARCHAR2(255),
  COMPONENT  VARCHAR2(255),
  ICON       VARCHAR2(64),
  SORT_NO    NUMBER(8),
  PERMISSION VARCHAR2(128),
  VISIBLE    NUMBER(1)    DEFAULT 1
);

CREATE TABLE SYS_ORG (
  ID          NUMBER(19)   PRIMARY KEY,
  PARENT_ID   NUMBER(19),
  ORG_CODE    VARCHAR2(64),
  ORG_NAME    VARCHAR2(128),
  ORG_TYPE    VARCHAR2(32),
  SORT_NO     NUMBER(8),
  STATUS      NUMBER(1)    DEFAULT 1,
  TENANT_ID   NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0
);

CREATE TABLE SYS_USER_ROLE (
  ID      NUMBER(19) PRIMARY KEY,
  USER_ID NUMBER(19),
  ROLE_ID NUMBER(19)
);

CREATE TABLE SYS_ROLE_MENU (
  ID      NUMBER(19) PRIMARY KEY,
  ROLE_ID NUMBER(19),
  MENU_ID NUMBER(19)
);

-- 分配数据：用户↔项目显式授权（县域隔离 per-user 项目范围）
CREATE TABLE SYS_USER_PROJECT (
  ID         NUMBER(20) PRIMARY KEY,
  USER_ID    NUMBER(20) NOT NULL,
  PROJECT_ID NUMBER(20) NOT NULL
);

-- ============ 一卡通领域 ============
CREATE TABLE YKT_BANK (
  ID          NUMBER(19)   PRIMARY KEY,
  BANK_CODE   VARCHAR2(64),
  BANK_NAME   VARCHAR2(128),
  UNION_CODE  VARCHAR2(64),
  REGION_CODE VARCHAR2(32),
  STATUS      NUMBER(1)    DEFAULT 1,
  REMARK      VARCHAR2(255),
  TENANT_ID   NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0
);

CREATE TABLE YKT_VILLAGE (
  ID           NUMBER(19)   PRIMARY KEY,
  TOWN_ID      NUMBER(19),
  VILLAGE_CODE VARCHAR2(64),
  VILLAGE_NAME VARCHAR2(128),
  SORT_NO      NUMBER(8),
  STATUS       NUMBER(1)    DEFAULT 1,
  TENANT_ID    NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0
);

CREATE TABLE YKT_PROJECT (
  ID            NUMBER(19)   PRIMARY KEY,
  PROJECT_CODE  VARCHAR2(64),
  PROJECT_NAME  VARCHAR2(255),
  SHORT_NAME    VARCHAR2(200),
  POLICY_LEVEL  VARCHAR2(32),
  PROJECT_LEVEL VARCHAR2(32),
  DEPT_NAME     VARCHAR2(128),
  AUDIT_STATUS  VARCHAR2(32) DEFAULT 'DRAFT',
  INCLUDED      NUMBER(1)    DEFAULT 0,
  CATALOG_CODE  VARCHAR2(64),
  REMARK        VARCHAR2(255),
  TENANT_ID     NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0,
  COMPETENT_DEPT    VARCHAR2(128),
  GRANT_TYPE        VARCHAR2(64),
  BUDGET_SOURCE     VARCHAR2(128),
  TRACE_CODE        VARCHAR2(128),
  SUBSIDY_SCOPE     VARCHAR2(2000),
  POLICY_DOC_NAME   VARCHAR2(500),
  POLICY_DOC_NO     VARCHAR2(200),
  POLICY_FILE       VARCHAR2(500),
  SUBSIDY_STANDARD  VARCHAR2(2000),
  LAST_RESULT       VARCHAR2(100),
  CATALOG_NAME      VARCHAR2(255),
  AUDIT_STAGE       VARCHAR2(16),
  PIVOT_OFFICE_CODE VARCHAR2(16),
  PIVOT_OFFICE_NAME VARCHAR2(64)
);

CREATE TABLE YKT_BENEFICIARY (
  ID             NUMBER(19)   PRIMARY KEY,
  HOUSEHOLD_CODE VARCHAR2(64),
  HEAD_NAME      VARCHAR2(64),
  HEAD_ID_CARD   VARCHAR2(32),
  NAME           VARCHAR2(64),
  ID_CARD        VARCHAR2(32),
  SOCIAL_CARD    VARCHAR2(64),
  TOWN_ID        NUMBER(19),
  VILLAGE_ID     NUMBER(19),
  GROUP_NAME     VARCHAR2(32),
  GENDER         VARCHAR2(8),
  PHONE          VARCHAR2(32),
  AGE            NUMBER(5),
  RELATION       VARCHAR2(32),
  BANK_ID        NUMBER(19),
  ACCOUNT_NAME   VARCHAR2(64),
  BANK_ACCOUNT   VARCHAR2(64),
  STATUS         VARCHAR2(16) DEFAULT '1',
  REFERRED       NUMBER(1)    DEFAULT 0,
  REMARK         VARCHAR2(255),
  TENANT_ID      NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0,
  PUBLIC_ACCOUNT_NAME VARCHAR2(64),
  PUBLIC_ACCOUNT_NO   VARCHAR2(64),
  PUBLIC_BANK_ID      NUMBER(19),
  IS_DIBAO   VARCHAR2(2),
  IS_FILING  VARCHAR2(2),
  IS_TEKUN   VARCHAR2(2),
  IS_RURAL   VARCHAR2(2),
  HOUSE_INFO    VARCHAR2(255),
  FARMLAND_INFO VARCHAR2(255)
);

CREATE TABLE YKT_NOTICE (
  ID             NUMBER(19)   PRIMARY KEY,
  TITLE          VARCHAR2(255),
  FILE_URL       VARCHAR2(512),
  FILE_NAME      VARCHAR2(255),
  TARGET_ORG_IDS VARCHAR2(512),
  STATUS         NUMBER(1)    DEFAULT 1,
  TENANT_ID      NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0
);

CREATE TABLE YKT_BATCH (
  ID            NUMBER(19)   PRIMARY KEY,
  BATCH_CODE    VARCHAR2(64),
  BATCH_NAME    VARCHAR2(255),
  PROJECT_ID    NUMBER(19),
  TOWN_ID       NUMBER(19),
  STATUS        VARCHAR2(32) DEFAULT 'NEW',
  AUDIT_STAGE   VARCHAR2(32) DEFAULT 'TOWN_SUBMIT',
  LAST_RESULT   VARCHAR2(64),
  GRANT_TIME    TIMESTAMP,
  PLAN_AMOUNT   NUMBER(18,2),
  PLAN_COUNT    NUMBER(10),
  ACTUAL_AMOUNT NUMBER(18,2),
  ACTUAL_COUNT  NUMBER(10),
  REFUND_AMOUNT NUMBER(18,2),
  REMARK        VARCHAR2(255),
  TENANT_ID     NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0,
  RETURN_AMOUNT NUMBER(18,2),
  STOP_AMOUNT   NUMBER(18,2),
  FUND_TITLE    VARCHAR2(255),
  DEADLINE      VARCHAR2(10)
);

CREATE TABLE YKT_ROSTER (
  ID             NUMBER(19)   PRIMARY KEY,
  BATCH_ID       NUMBER(19),
  BENEFICIARY_ID NUMBER(19),
  NAME           VARCHAR2(64),
  ID_CARD        VARCHAR2(32),
  SOCIAL_CARD    VARCHAR2(64),
  VILLAGE_ID     NUMBER(19),
  STANDARD       NUMBER(18,2),
  AMOUNT         NUMBER(18,2),
  AUDIT_STATUS   VARCHAR2(32) DEFAULT 'DRAFT',
  PAY_STATUS     VARCHAR2(32) DEFAULT 'NONE',
  TENANT_ID      NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0
);

-- 花名册明细（发放明细）
CREATE TABLE YKT_GRANT_DETAIL (
  ID NUMBER(19) PRIMARY KEY,
  BATCH_ID NUMBER(19), BATCH_CODE VARCHAR2(64), SORT_NO NUMBER(10),
  PAY_STATUS VARCHAR2(32),
  HOLDER_NAME VARCHAR2(128), HOLDER_ID_CARD VARCHAR2(32),
  PAYEE_NAME VARCHAR2(128), PAYEE_ID_CARD VARCHAR2(32),
  BANK_ACCOUNT VARCHAR2(64), BANK_NAME VARCHAR2(200),
  VILLAGE_NAME VARCHAR2(160), GROUP_NAME VARCHAR2(64),
  BENEFICIARY_NAME VARCHAR2(128), BENEFICIARY_ID_CARD VARCHAR2(32),
  PHONE VARCHAR2(32), RESIDENCE VARCHAR2(255), AGE NUMBER(5),
  STANDARD NUMBER(18,2), AMOUNT NUMBER(18,2), FILL_DATE DATE,
  RELATIONSHIP VARCHAR2(40), REMARK VARCHAR2(255),
  TENANT_ID NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0,
  FAIL_REASON VARCHAR2(200),
  RETRY_TIMES NUMBER(3) DEFAULT 0,
  STOP_REASON VARCHAR2(200),
  EXT_JSON VARCHAR2(2000)
);

-- 发放表定义：每个项目一套清册导入模板列定义（固定列不可删改标识/类型/绑定，自由列可自定义）
CREATE TABLE YKT_TPL_ITEM (
  ID            NUMBER(19)    PRIMARY KEY,
  PROJECT_ID    NUMBER(19)    NOT NULL,
  ITEM_KEY      VARCHAR2(40)  NOT NULL,
  ITEM_LABEL    VARCHAR2(120) NOT NULL,
  COL_TYPE      VARCHAR2(20)  DEFAULT 'text' NOT NULL,
  REQUIRED_FLAG NUMBER(1)     DEFAULT 0,
  BIND_FIELD    VARCHAR2(40),
  FIXED_FLAG    NUMBER(1)     DEFAULT 0,
  SORT_NO       NUMBER(5)     DEFAULT 0,
  REMARK        VARCHAR2(400),
  ENUM_VALUES   VARCHAR2(400),
  FORMULA       VARCHAR2(200),
  COL_GROUP     VARCHAR2(20),
  TENANT_ID     NUMBER(19),
  CREATE_TIME   TIMESTAMP,
  UPDATE_TIME   TIMESTAMP,
  CREATE_BY     NUMBER(19)
);

CREATE TABLE YKT_PROJECT_QUOTA (
  ID             NUMBER(19)   PRIMARY KEY,
  PROJECT_ID     NUMBER(19),
  INDICATOR_CODE VARCHAR2(64),
  INDICATOR_NAME VARCHAR2(255),
  PRIORITY       NUMBER(8),
  QUOTA_AMOUNT   NUMBER(18,2),
  TENANT_ID      NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0,
  INDICATOR_ID   NUMBER,
  USE_RULE       VARCHAR2(20)
);

CREATE TABLE YKT_PAYMENT_APPLY (
  ID          NUMBER(19)   PRIMARY KEY,
  APPLY_NO    VARCHAR2(64),
  BATCH_ID    NUMBER(19),
  PROJECT_ID  NUMBER(19),
  AMOUNT      NUMBER(18,2),
  PAYEE       VARCHAR2(255),
  USAGE       VARCHAR2(255),
  STATUS      VARCHAR2(32) DEFAULT 'PENDING_SUBMIT',
  TENANT_ID   NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0
);

-- 支付申请明细（逐指标扣减）
CREATE TABLE YKT_PAY_APPLY_DETAIL (
  ID            NUMBER   PRIMARY KEY,
  APPLY_ID      NUMBER,
  INDICATOR_ID  NUMBER,
  INDICATOR_NO  VARCHAR2(100),
  DEDUCT_AMOUNT NUMBER(18,2) DEFAULT 0,
  TENANT_ID     NUMBER,
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER, UPDATE_BY NUMBER, DELETED NUMBER DEFAULT 0
);

-- 预算指标额度
CREATE TABLE YKT_INDICATOR (
  ID               NUMBER   PRIMARY KEY,
  INDICATOR_NO     VARCHAR2(100),
  GOV_ECON_CODE    VARCHAR2(20),
  GOV_ECON_NAME    VARCHAR2(120),
  DEPT_ECON_CODE   VARCHAR2(20),
  DEPT_ECON_NAME   VARCHAR2(120),
  BUDGET_PROJECT   VARCHAR2(200),
  FUND_NATURE      VARCHAR2(120),
  ISSUED_AMOUNT    NUMBER(18,2) DEFAULT 0,
  FROZEN_AMOUNT    NUMBER(18,2) DEFAULT 0,
  PAID_AMOUNT      NUMBER(18,2) DEFAULT 0,
  AVAILABLE_AMOUNT NUMBER(18,2) DEFAULT 0,
  BUDGET_UNIT      VARCHAR2(200),
  INDICATOR_DESC   VARCHAR2(400),
  HOT_CLASS_NAME   VARCHAR2(50),
  TENANT_ID        NUMBER,
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER, UPDATE_BY NUMBER, DELETED NUMBER DEFAULT 0
);

-- 发放数据审核：审核流水
CREATE TABLE YKT_AUDIT_LOG (
  ID              NUMBER(19)   PRIMARY KEY,
  BATCH_ID        NUMBER(19),
  SEQ_NO          NUMBER(8),
  DONE_STATION    VARCHAR2(64),
  OPERATOR        VARCHAR2(64),
  OP_TYPE         VARCHAR2(32),
  OP_RESULT       VARCHAR2(64),
  OPINION         VARCHAR2(255),
  OP_TIME         TIMESTAMP,
  PENDING_STATION VARCHAR2(64),
  TENANT_ID       NUMBER(19),
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER(19), UPDATE_BY NUMBER(19), DELETED NUMBER(1) DEFAULT 0
);

-- 补贴项目审核流水
CREATE TABLE YKT_PROJECT_AUDIT_LOG (
  ID              NUMBER   PRIMARY KEY,
  PROJECT_ID      NUMBER,
  SEQ_NO          NUMBER,
  DONE_STATION    VARCHAR2(64),
  OPERATOR        VARCHAR2(64),
  OP_TYPE         VARCHAR2(32),
  OP_RESULT       VARCHAR2(64),
  OPINION         VARCHAR2(255),
  OP_TIME         TIMESTAMP,
  PENDING_STATION VARCHAR2(64),
  TENANT_ID       NUMBER,
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER, UPDATE_BY NUMBER, DELETED NUMBER DEFAULT 0
);

-- 项目↔政策 多对多
CREATE TABLE YKT_PROJECT_POLICY (
  ID         NUMBER(19)   PRIMARY KEY,
  PROJECT_ID NUMBER(19) NOT NULL,
  POLICY_ID  NUMBER(19) NOT NULL,
  TENANT_ID  NUMBER(19),
  CREATE_TIME TIMESTAMP, CREATE_BY NUMBER(19)
);

-- 政策基础库
CREATE TABLE YKT_POLICY (
  ID             NUMBER   PRIMARY KEY,
  POLICY_NO      VARCHAR2(100),
  TITLE          VARCHAR2(500),
  POLICY_LEVEL   VARCHAR2(10),
  POLICY_YEAR    VARCHAR2(10),
  PUBLISH_DATE   VARCHAR2(20),
  END_DATE       VARCHAR2(20),
  COMPETENT_DEPT VARCHAR2(200),
  SHORT_NAME     VARCHAR2(200),
  STATUS         VARCHAR2(10) DEFAULT '1',
  CONTENT        CLOB,
  REMARK         VARCHAR2(500),
  TENANT_ID      NUMBER,
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER, UPDATE_BY NUMBER, DELETED NUMBER DEFAULT 0
);

-- 机构字典（下拉数据源）
CREATE TABLE YKT_AGENCY (
  GUID        VARCHAR2(60) PRIMARY KEY,
  CODE        VARCHAR2(20),
  NAME        VARCHAR2(300),
  SUPER_GUID  VARCHAR2(60),
  LEVEL_NO    NUMBER,
  IS_SUBSIDY  VARCHAR2(2),
  IS_LEAF     NUMBER,
  ORDER_NUM   NUMBER,
  STATUS      NUMBER,
  TOWN_ID     NUMBER,
  COUNTY_CODE VARCHAR2(20)
);

-- 中央项目目录
CREATE TABLE YKT_CENTRAL_PROJECT (
  ID             NUMBER   PRIMARY KEY,
  PROJECT_CODE   VARCHAR2(64),
  PROJECT_NAME   VARCHAR2(255),
  CATEGORY       VARCHAR2(32),
  COMPETENT_DEPT VARCHAR2(128),
  POLICY_BASIS   VARCHAR2(500),
  TENANT_ID      NUMBER,
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER, UPDATE_BY NUMBER, DELETED NUMBER DEFAULT 0
);

-- 股室字典
CREATE TABLE YKT_OFFICE (
  ID          NUMBER   PRIMARY KEY,
  OFFICE_CODE VARCHAR2(16),
  OFFICE_NAME VARCHAR2(64),
  SORT_NO     NUMBER,
  TENANT_ID   NUMBER,
  CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP, CREATE_BY NUMBER, UPDATE_BY NUMBER, DELETED NUMBER DEFAULT 0
);

-- ============ 索引 ============
CREATE INDEX IDX_SUP_USER          ON SYS_USER_PROJECT(USER_ID);
CREATE INDEX IDX_AUDITLOG_BATCH    ON YKT_AUDIT_LOG(BATCH_ID);
CREATE INDEX IDX_BATCH_TOWN        ON YKT_BATCH(TOWN_ID);
CREATE INDEX IDX_BENE_TOWN         ON YKT_BENEFICIARY(TOWN_ID);
CREATE INDEX IX_GD_BATCH           ON YKT_GRANT_DETAIL(BATCH_ID);
CREATE INDEX IDX_YKT_PROJ_LOG_PID  ON YKT_PROJECT_AUDIT_LOG(PROJECT_ID);
CREATE INDEX IX_PROJ_POLICY_PID    ON YKT_PROJECT_POLICY(PROJECT_ID);
CREATE UNIQUE INDEX UX_PROJ_POLICY ON YKT_PROJECT_POLICY(PROJECT_ID, POLICY_ID);
CREATE INDEX IDX_ROSTER_BATCH      ON YKT_ROSTER(BATCH_ID);
-- 国标「51项」补贴项目目录（实际 55 项，2 开头国标码；51项发放表/补贴录入菜单数据源）
CREATE TABLE YKT_STD_ITEM (
  CODE       VARCHAR2(20)  PRIMARY KEY,
  ITEM_NAME  VARCHAR2(200) NOT NULL,
  SHORT_NAME VARCHAR2(100),
  SORT_NO    NUMBER(5)     DEFAULT 0
);

CREATE UNIQUE INDEX UX_TPL_ITEM_KEY ON YKT_TPL_ITEM(PROJECT_ID, ITEM_KEY);
CREATE INDEX IX_TPL_ITEM_PID       ON YKT_TPL_ITEM(PROJECT_ID);
